### PR TITLE
input coordinates and preliminary mc code added

### PR DESCRIPTION
**Pull request by vpasumarthi**
NIST Input coordinates for 800 particles along with preliminary MC code used for session 01 have been added.

### CODE REVIEW

**Review by dibyendu92 — COMMENTED** [review]
it looks good

**Comment by cgseitz** [comment]
good work

**Review by cgseitz — APPROVED** [review]

**Review by cgseitz — APPROVED** [review]

**Review by dibyendu92 — COMMENTED** [review]
@cgseitz  should we accept it?

**Review by cgseitz — APPROVED** [review]

**Comment by cgseitz** [comment]
the Travis CI check failed...oooops

**Review by dibyendu92 — COMMENTED** [review]
@cgseitz  should we revert the merge?

**Comment by vpasumarthi** [comment]
Why can't Travis be like @cgseitz and approve? :P

**Pull request merged**
