### PR TITLE
added setup.py

### PR DESCRIPTION
**Pull request by vpasumarthi**
Modified setup.py from Daniel's tutorial repository and pushed.

### CODE REVIEW

**Review by cgseitz — DISMISSED** [review]

**Review by dibyendu92 — COMMENTED** [review]
should we change (author) = MM2 team?

**Comment by vpasumarthi** [comment]
Sure. Why not?

**Comment by cgseitz** [comment]
@dibyendu92 let's get on it

**Review by cgseitz — APPROVED** [review]

**Review by dibyendu92 — APPROVED** [review]

**Comment by dibyendu92** [comment]
So I have accepted the change from @vpasumarthi

**Pull request merged**
